"""Element data, transcoded from Avogadro 2's avogadro/core/elementdata.h.

Index = atomic number; index 0 is the "Xx" dummy atom. 119 entries (Xx + H..Og).

Provenance (BSD 3-Clause, Copyright 2011-2020 Kitware, Inc. - see
THIRD_PARTY_NOTICES.md):
  https://github.com/OpenChemistry/avogadrolibs  avogadro/core/elementdata.h
- RADII_VDW:      Alvarez, Dalton Trans. 2013, 42, 8617 (doi:10.1039/C3DT50599E)
- RADII_COVALENT: Pyykko & Atsumi, Chem. Eur. J. 2009 (doi:10.1002/chem.200800987)
- COLORS: Jmol/CPK scheme with Avogadro's tweaks (H off-white for light
  backgrounds, C 50% grey, F shifted blue for contrast with Cl).

GENERATED FILE - do not hand-edit values. Regenerated by gen_elements.py from
the upstream header (fetched 2026-07-30).
"""

ELEMENT_COUNT = 119

SYMBOLS = (
    "Xx", "H", "He", "Li", "Be", "B", "C", "N", "O", "F",
    "Ne", "Na", "Mg", "Al", "Si", "P", "S", "Cl", "Ar", "K",
    "Ca", "Sc", "Ti", "V", "Cr", "Mn", "Fe", "Co", "Ni", "Cu",
    "Zn", "Ga", "Ge", "As", "Se", "Br", "Kr", "Rb", "Sr", "Y",
    "Zr", "Nb", "Mo", "Tc", "Ru", "Rh", "Pd", "Ag", "Cd", "In",
    "Sn", "Sb", "Te", "I", "Xe", "Cs", "Ba", "La", "Ce", "Pr",
    "Nd", "Pm", "Sm", "Eu", "Gd", "Tb", "Dy", "Ho", "Er", "Tm",
    "Yb", "Lu", "Hf", "Ta", "W", "Re", "Os", "Ir", "Pt", "Au",
    "Hg", "Tl", "Pb", "Bi", "Po", "At", "Rn", "Fr", "Ra", "Ac",
    "Th", "Pa", "U", "Np", "Pu", "Am", "Cm", "Bk", "Cf", "Es",
    "Fm", "Md", "No", "Lr", "Rf", "Db", "Sg", "Bh", "Hs", "Mt",
    "Ds", "Rg", "Cn", "Nh", "Fl", "Mc", "Lv", "Ts", "Og",
)

NAMES = (
    "Dummy", "Hydrogen", "Helium", "Lithium", "Beryllium",
    "Boron", "Carbon", "Nitrogen", "Oxygen", "Fluorine",
    "Neon", "Sodium", "Magnesium", "Aluminium", "Silicon",
    "Phosphorus", "Sulfur", "Chlorine", "Argon", "Potassium",
    "Calcium", "Scandium", "Titanium", "Vanadium", "Chromium",
    "Manganese", "Iron", "Cobalt", "Nickel", "Copper",
    "Zinc", "Gallium", "Germanium", "Arsenic", "Selenium",
    "Bromine", "Krypton", "Rubidium", "Strontium", "Yttrium",
    "Zirconium", "Niobium", "Molybdenum", "Technetium", "Ruthenium",
    "Rhodium", "Palladium", "Silver", "Cadmium", "Indium",
    "Tin", "Antimony", "Tellurium", "Iodine", "Xenon",
    "Caesium", "Barium", "Lanthanum", "Cerium", "Praseodymium",
    "Neodymium", "Promethium", "Samarium", "Europium", "Gadolinium",
    "Terbium", "Dysprosium", "Holmium", "Erbium", "Thulium",
    "Ytterbium", "Lutetium", "Hafnium", "Tantalum", "Tungsten",
    "Rhenium", "Osmium", "Iridium", "Platinum", "Gold",
    "Mercury", "Thallium", "Lead", "Bismuth", "Polonium",
    "Astatine", "Radon", "Francium", "Radium", "Actinium",
    "Thorium", "Protactinium", "Uranium", "Neptunium", "Plutonium",
    "Americium", "Curium", "Berkelium", "Californium", "Einsteinium",
    "Fermium", "Mendelevium", "Nobelium", "Lawrencium", "Rutherfordium",
    "Dubnium", "Seaborgium", "Bohrium", "Hassium", "Meitnerium",
    "Darmstadtium", "Roentgenium", "Copernicium", "Nihonium", "Flerovium",
    "Moscovium", "Livermorium", "Tennessine", "Oganesson",
)

# Standard atomic weights (amu).
MASSES = (
    0.0, 1.00784, 4.002602, 6.94, 9.012183, 10.81,
    12.011, 14.007, 15.999, 18.998403, 20.1797, 22.989769,
    24.305, 26.981538, 28.085, 30.973762, 32.06, 35.45,
    39.94, 39.0983, 40.078, 44.955908, 47.867, 50.9415,
    51.9961, 54.938043, 55.845, 58.933194, 58.6934, 63.546,
    65.38, 69.723, 72.63, 74.921595, 78.971, 79.904,
    83.798, 85.4678, 87.62, 88.90584, 91.224, 92.90637,
    95.95, 97.0, 101.07, 102.90549, 106.42, 107.8682,
    112.414, 114.818, 118.71, 121.76, 127.6, 126.90447,
    131.293, 132.90447, 137.327, 138.90547, 140.116, 140.90766,
    144.242, 145.0, 150.36, 151.964, 157.25, 158.92535,
    162.5, 164.93033, 167.259, 168.93422, 173.045, 174.9668,
    178.486, 180.94788, 183.84, 186.207, 190.23, 192.217,
    195.084, 196.96657, 200.592, 204.38, 207.2, 208.9804,
    209.0, 210.0, 222.0, 223.0, 226.0, 227.0,
    232.0377, 231.0358, 238.02891, 237.0, 244.0, 243.0,
    247.0, 247.0, 251.0, 252.0, 257.0, 258.0,
    259.0, 262.0, 267.0, 270.0, 269.0, 270.0,
    270.0, 278.0, 281.0, 281.0, 285.0, 286.0,
    289.0, 289.0, 293.0, 293.0, 294.0,
)

# Van der Waals radii (Angstrom) - drives displayed sphere size.
RADII_VDW = (
    0.69, 1.2, 1.43, 2.12, 1.98, 1.91, 1.77, 1.66,
    1.5, 1.46, 1.58, 2.5, 2.51, 2.25, 2.19, 1.9,
    1.89, 1.82, 1.83, 2.73, 2.62, 2.58, 2.46, 2.42,
    2.45, 2.45, 2.44, 2.4, 2.4, 2.38, 2.39, 2.32,
    2.29, 1.88, 1.82, 1.86, 2.25, 3.21, 2.84, 2.75,
    2.52, 2.56, 2.45, 2.44, 2.46, 2.44, 2.15, 2.53,
    2.49, 2.43, 2.42, 2.47, 1.99, 2.04, 2.06, 3.48,
    3.03, 2.98, 2.88, 2.92, 2.95, 2.9, 2.87, 2.83,
    2.79, 2.87, 2.81, 2.83, 2.79, 2.8, 2.74, 2.63,
    2.53, 2.57, 2.49, 2.48, 2.41, 2.29, 2.32, 2.45,
    2.47, 2.6, 2.54, 2.5, 2.5, 2.5, 2.5, 2.5,
    2.8, 2.93, 2.88, 2.71, 2.82, 2.81, 2.83, 3.05,
    3.38, 3.05, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0,
    3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0,
    3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0,
)

# Covalent radii (Angstrom) - drives bond perception.
RADII_COVALENT = (
    0.18, 0.32, 0.46, 1.33, 1.02, 0.85, 0.75, 0.71,
    0.63, 0.64, 0.67, 1.55, 1.39, 1.26, 1.16, 1.11,
    1.03, 0.99, 0.96, 1.96, 1.71, 1.48, 1.36, 1.34,
    1.22, 1.19, 1.16, 1.11, 1.1, 1.12, 1.18, 1.24,
    1.21, 1.21, 1.16, 1.14, 1.17, 2.1, 1.85, 1.63,
    1.54, 1.47, 1.38, 1.28, 1.25, 1.25, 1.2, 1.28,
    1.36, 1.42, 1.4, 1.4, 1.36, 1.33, 1.31, 2.32,
    1.96, 1.8, 1.63, 1.76, 1.74, 1.73, 1.72, 1.68,
    1.69, 1.68, 1.67, 1.66, 1.65, 1.64, 1.7, 1.62,
    1.52, 1.46, 1.37, 1.31, 1.29, 1.22, 1.23, 1.24,
    1.33, 1.44, 1.44, 1.51, 1.45, 1.47, 1.42, 2.23,
    2.01, 1.86, 1.75, 1.69, 1.7, 1.71, 1.72, 1.66,
    1.66, 1.68, 1.68, 1.65, 1.67, 1.73, 1.76, 1.61,
    1.57, 1.49, 1.43, 1.41, 1.34, 1.29, 1.28, 1.21,
    1.22, 1.36, 1.43, 1.62, 1.75, 1.65, 1.57,
)

# Display colours, RGB 0-255.
COLORS = (
    (17, 127, 178), (240, 240, 240), (217, 255, 255), (204, 128, 255),
    (194, 255, 0), (255, 181, 181), (127, 127, 127), (48, 80, 255),
    (255, 13, 13), (178, 255, 255), (178, 227, 245), (171, 91, 242),
    (138, 255, 0), (191, 166, 166), (240, 200, 160), (255, 128, 0),
    (255, 255, 48), (31, 240, 31), (128, 209, 227), (143, 64, 212),
    (61, 255, 0), (230, 230, 230), (191, 194, 199), (166, 166, 171),
    (138, 153, 199), (156, 122, 199), (224, 102, 51), (240, 144, 160),
    (80, 208, 80), (200, 128, 51), (125, 128, 176), (194, 143, 143),
    (102, 143, 143), (189, 128, 227), (255, 161, 0), (166, 41, 41),
    (92, 184, 209), (112, 46, 176), (0, 255, 0), (148, 255, 255),
    (148, 224, 224), (115, 194, 201), (84, 181, 181), (59, 158, 158),
    (36, 143, 143), (10, 125, 140), (0, 105, 133), (192, 192, 192),
    (255, 217, 143), (166, 117, 115), (102, 128, 128), (158, 99, 181),
    (211, 122, 0), (148, 0, 148), (66, 158, 176), (87, 23, 143),
    (0, 201, 0), (112, 212, 255), (255, 255, 199), (217, 255, 199),
    (199, 255, 199), (163, 255, 199), (143, 255, 199), (97, 255, 199),
    (69, 255, 199), (48, 255, 199), (31, 255, 199), (0, 255, 156),
    (0, 230, 117), (0, 212, 82), (0, 191, 56), (0, 171, 36),
    (77, 194, 255), (77, 166, 255), (33, 148, 214), (38, 102, 150),
    (38, 102, 150), (23, 84, 135), (208, 208, 224), (255, 209, 35),
    (184, 194, 208), (166, 84, 77), (87, 89, 97), (158, 79, 181),
    (171, 92, 0), (117, 79, 69), (66, 130, 150), (66, 0, 102),
    (0, 124, 0), (112, 170, 249), (0, 186, 255), (0, 160, 255),
    (0, 142, 255), (0, 127, 255), (0, 107, 255), (84, 91, 242),
    (119, 91, 226), (137, 79, 226), (160, 53, 211), (178, 30, 211),
    (178, 30, 186), (178, 12, 165), (188, 12, 135), (198, 0, 102),
    (204, 0, 89), (209, 0, 79), (216, 0, 68), (224, 0, 56),
    (229, 0, 45), (232, 0, 38), (234, 0, 35), (237, 0, 33),
    (239, 0, 30), (242, 0, 28), (244, 0, 25), (247, 0, 22),
    (249, 0, 20), (252, 0, 17), (255, 0, 15),
)

_SYMBOL_TO_Z = {s.lower(): z for z, s in enumerate(SYMBOLS)}
# Full names, lower-cased. Typing "carbon" (or "CARBON", or "Carbon") is a
# perfectly reasonable way to ask for C, and it disambiguates the pairs that
# trip people up at the keyboard — "co" is cobalt, "carbon" cannot be.
_NAME_TO_Z = {n.lower(): z for z, n in enumerate(NAMES) if z > 0}
# Spellings Avogadro/PubChem/US sources use that our table does not.
_NAME_TO_Z.update({"aluminum": 13, "cesium": 55, "sulphur": 16})


def atomic_number(symbol):
    # type: (str) -> int
    """Atomic number for an element symbol; 0 (dummy) if unknown.

    Tolerant of case and trailing digits/labels ("C1", "cl2" -> 6, 17), the
    same convention ORCA Workbench's transform module uses."""
    letters = "".join(ch for ch in str(symbol) if ch.isalpha())
    if len(letters) >= 2:
        z = _SYMBOL_TO_Z.get(letters[:2].lower())
        if z:
            return z
    return _SYMBOL_TO_Z.get(letters[:1].lower(), 0)


def from_text(text):
    # type: (str) -> int
    """Atomic number for a symbol OR a full element name; 0 if unknown.

    Case-insensitive on both, so "FE", "fe", "Iron" and "IRON" all give 26.
    Names are checked FIRST: `atomic_number` is deliberately tolerant of
    trailing junk, so it happily reads "nitrogen" as N — which is right by
    luck, while "iron" would come out as iodine. Anything that is not a whole
    name falls through to the tolerant symbol reading.
    """
    clean = "".join(ch for ch in str(text) if ch.isalpha()).lower()
    if not clean:
        return 0
    z = _NAME_TO_Z.get(clean)
    if z:
        return z
    # A real symbol is 1-2 letters, so stripping digits off "C1"/"Cl2" leaves
    # at most two. Anything longer that did NOT match a name is a mistyped
    # name, not a symbol with junk on the end — falling through to the
    # tolerant reading would turn "unobtainium" into uranium.
    if len(clean) > 2:
        return 0
    return atomic_number(clean)


def symbol_from_text(text):
    # type: (str) -> str
    """Canonical symbol ("Fe") for a symbol or name; "" if unknown."""
    z = from_text(text)
    return SYMBOLS[z] if z else ""


def symbol(z):
    # type: (int) -> str
    return SYMBOLS[z] if 0 <= z < ELEMENT_COUNT else "Xx"


def name(z):
    # type: (int) -> str
    return NAMES[z] if 0 <= z < ELEMENT_COUNT else "Dummy"


def mass(z):
    # type: (int) -> float
    return MASSES[z] if 0 <= z < ELEMENT_COUNT else 0.0


def radius_vdw(z):
    # type: (int) -> float
    return RADII_VDW[z] if 0 <= z < ELEMENT_COUNT else 1.5


def radius_covalent(z):
    # type: (int) -> float
    return RADII_COVALENT[z] if 0 <= z < ELEMENT_COUNT else 1.5


def color(z):
    # type: (int) -> tuple
    """RGB 0-255 display colour."""
    return COLORS[z] if 0 <= z < ELEMENT_COUNT else COLORS[0]


def color_f(z):
    # type: (int) -> tuple
    """RGB 0.0-1.0 display colour (for GL)."""
    r, g, b = color(z)
    return (r / 255.0, g / 255.0, b / 255.0)
